# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=models.TextField(default='{}'),
        ),
    ]
